### PR TITLE
Updated Iteration 1 files

### PR DESCRIPTION
**Pull request by nsingl02**
Changed some variable names.

### CODE REVIEW

**Review by nhuthuynh — CHANGES_REQUESTED** [review]
Please have a look again code style guideline

**Comment by nhuthuynh** [comment]
@nsingl02 please check this file and follow the guidelines to fix the assignment items.
https://interact2.csu.edu.au/webapps/blackboard/execute/content/file?cmd=view&content_id=_2343317_1&course_id=_32947_1

**Comment by nsingl02** [comment]
changes are made in the commits

**Review by nhuthuynh — APPROVED** [review]

**Comment by nhuthuynh** [comment]
It is much better now!

**Pull request merged**
