### PR TITLE
Nipun

### PR DESCRIPTION
**Pull request by nsingl02**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Change ID to bookId

**Review by ghost — CHANGES_REQUESTED** [review]
This is wrong. Change it back to ON_LOAN

**Comment by nsingl02** [comment]
Changes done!

**Review by ghost — APPROVED** [review]

**Comment by nhuthuynh** [comment]
@Nylanderjonathan @nsingl02 @mendefrost please pull the latest code for your local master and branch.

**Pull request merged**
